import { defineConfig, devices } from "@playwright/test";
import "dotenv/config";

// Generated by /trace2e from the "recorded-flow" recording (matched as the latest trace
// for the requested name "test-product"). baseURL + viewport come from the recording.
export default defineConfig({
  testDir: "./tests",
  // Daemon/dashboard tests have their own config (playwright.daemon.config.ts).
  testIgnore: ["daemon-api.spec.ts", "dashboard.spec.ts"],
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: "html",
  use: {
    baseURL: "https://web-client-v3-0-a0kxfhgta-webclient3.vercel.app",
    viewport: { width: 1449, height: 869 },
    trace: "on-first-retry",
    screenshot: "only-on-failure",
  },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
});
