import { test, expect } from "@playwright/test";

/**
 * Product purchase → checkout flow for the ZeBrands web client.
 *
 * Generated by /trace2e from the latest recording (internally named "recorded-flow";
 * no trace was literally named "test-product", so the most recent one was used).
 *
 * The raw recording was 43 steps and contained capture noise that has been pruned for
 * maintainability — each pruned item is noted inline as `// pruned:` so nothing is hidden:
 *   - an accidental tab switch to meet.google.com (raw step 34)
 *   - several partial re-types of the postal code ("324", "32544", "", "32545", "325")
 *     collapsed to the final value "32500"
 *   - a duplicate "Almohadas" click and a stray click on #__next
 *   - fragile positional icon/div clicks (`div > div:nth-of-type(1)`, `span > button > svg`)
 *     that opened drawers/menus; the robust link/button path is used instead. If a drawer
 *     needs opening between steps, uncomment the `// raw:` lines.
 *
 * The recorded login email was captured as a literal value. Because it is personal data
 * and a login identity, it has been parameterized to process.env.TEST_EMAIL (best practice)
 * rather than hardcoded. Set it in .env before running.
 */

const TEST_EMAIL = process.env.TEST_EMAIL;

test.beforeAll(() => {
  expect(TEST_EMAIL, "Set TEST_EMAIL in .env (see .env.example)").toBeTruthy();
});

test("product purchase and checkout", async ({ page }) => {
  await test.step("open home and go to the Almohadas category", async () => {
    await page.goto("/");
    // pruned: raw steps 1-3, 6-9 were positional div/svg clicks that navigated the menu;
    // the category link below is the robust equivalent. pruned: duplicate "Almohadas" (step 5).
    await page.getByText("Almohadas").first().click();
    await expect(page).toHaveURL(/\/almohadas/);
  });

  await test.step("open the 'Almohada Cool Flip' product", async () => {
    // raw: page.locator('div:nth-of-type(2) > a > div:nth-of-type(1) > img') — replaced with
    // a href-based locator derived from the destination URL (more resilient to layout).
    await page.locator('a[href*="almohada-cool-flip"]').first().click();
    await expect(page).toHaveURL(/\/comprar\/almohada-cool-flip/);
  });

  await test.step("add the product to the cart and continue", async () => {
    // pruned: stray click on #__next (raw step 13).
    await page.getByRole("button", { name: "Agregar al carrito" }).click();
    // raw: two icon clicks opened the cart drawer (steps 15-16). Uncomment if needed:
    // await page.locator('span:nth-of-type(2) > button svg').click();
    // await page.locator('span > button svg').first().click();
    await page.getByRole("button", { name: "Continuar" }).click();
  });

  await test.step("log in with email", async () => {
    await page.getByRole("link", { name: "Iniciar sesión con correo" }).click();
    await expect(page).toHaveURL(/\/login\/email/);
    await page.getByLabel("Correo electrónico").fill(TEST_EMAIL!);
    await page.getByRole("button", { name: "Continuar" }).click();
    await page.getByRole("button", { name: "Confirmar" }).click();
    await page.getByRole("button", { name: "Paso siguiente: Entrega" }).click();
    await expect(page).toHaveURL(/\/checkout/);
  });

  await test.step("enter delivery postal code and proceed", async () => {
    // pruned: partial re-types "324"/"32544"/""/"32545"/"325" and the accidental
    // meet.google.com navigation (raw step 34); collapsed to the final value.
    await page.getByLabel("Escribe código postal *").fill("32500");
    await page.getByRole("button", { name: "Continuar" }).click();
    await page.getByRole("button", { name: "Confirmar" }).click();
    await page.getByRole("button", { name: "Paso siguiente: Entrega" }).click();
  });
});
